# Site settings
title: Lyndell.US
email: web@Lyndell.US
description: > # this means to ignore newlines until "baseurl:"

  I am Lyndell Rottmann. I like to program.

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://Lyndell.US" # the base hostname & protocol for your site
twitter_username: LyndellNET
github_username:  lyndell

encoding: US-ASCII

# Build settings
markdown: kramdown

# Github Flavored Markdown
kramdown:
  input: GFM

