# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        pretty

kramdown:
  input: GFM

# Site settings
title:            Nuclear Powered Brain
tagline:          "Fueled by chili and cooled by beer."
description:      "The Nuclear Powered Brain:  Fueled by chili and cooled by beer."
baseurl:          "/" # the subpath of your site, e.g. /blog/
url:              "http://nuclearpoweredbrain.com" # the base hostname & protocol for your site
paginate:         5

author:
  name:           'Lyndell'
  url:            https://twitter.com/LyndellNET
  #email:         your-email@domain.com
  #twitter_username: LyndellUS
  #github_username:  lyndell

# Custom vars
version:          3.0.0

github:
#  repo:           https://github.com/lyndell
